export const crossingBordersContent = `Crossing borders: family migration strategies and routes from Burma to the US

Manashi Ray To cite this article: Manashi Ray (2017): Crossing borders: family migration strategies and routes from Burma to the US, Journal of Ethnic and Migration Studies, DOI: 10.1080/1369183X.2017.1314815 To link to this article: http://dx.doi.org/10.1080/1369183X.2017.1314815

Published online: 15 Apr 2017.

Submit your article to this journal

View related articles

View Crossmark data

Crossing borders: family migration strategies and routes from Burma to the US Manashi Ray Department of Social and Behavioural Sciences, West Virginia State University, Institute, WV, USA ABSTRACT Over the last 35 years, the US has been the top recipient country for refugee resettlement. Despite political ambivalence about refugee admittance and their integration into America’s sociocultural fabric, little is known in refugee literature about how receiving countries’ refugee and asylum policies structure refugee migratory processes and flows from countries of origin. Based on 21 indepth interviews and group discussions with Chin-Burmese families, this paper traces migratory strategies and routes from Northern Burma to the US by examining the role of class, family dynamics, cross-border connections and social capital in migratory decision-making for irregular border-crossings and endurance as transit migrants. Additionally, I analyse the critical functions of intermediary social actors and institutions, particularly faith and community-based organisations, for gaining entry to destination countries. I show that examining Chin refugees’ agency and premigratory motives demonstrates the heterogeneity of the refugee population, justifying Chimamanda Adichie’s claim that ‘nobody is just a refugee’.

ARTICLE HISTORY Received 2 July 2016 Accepted 30 March 2017 KEYWORDS Chin-Burmese refugees/ asylees; migratory strategies; intermediary actors; faithbased organisations; transit migrants

Introduction This paper studies Burmese refugees, one of the largest groups resettled in the US since 2002. According to the US Refugee Processing Center, 15% of refugees resettled in the US in 2016 came from Burma. Routine persecution by Burma’s military government motivated them to seek refuge in neighbouring countries and throughout the region (Zong and Batalova 2015; International Rescue Committee [IRC] 2012).1 Using the case of Chin-Burmese refugees resettled in the US Midwest since 2001, I examine the premigratory decision-making process and how family dynamics, class, migration motives, conditions in the local ‘context of exit’ and meso-level social actors play definitive roles in refugees’ and asylees’ migratory outcomes. I also investigate how receiving countries’ asylum and refugee policies influence the migratory process, an aspect migration scholars largely ignore because of the bureaucratic dichotomy between labour migrants and refugees and their relationships to the state. For this study, I adapt the definition of the ‘context of exit’ of Portes and Rumbaut (2006) to include migrants’ motivations, the area of origin’s socio-economic conditions and the sending country’s attitude towards migrants.2 © 2017 Informa UK Limited, trading as Taylor & Francis Group CONTACT Manashi Ray mray3@wvstateu.edu; manashi.ray@gmail.com JOURNAL OF ETHNIC AND MIGRATION STUDIES, 2017 http://dx.doi.org/10.1080/1369183X.2017.1314815

By focusing on how Chin-Burmese families plan multi-stage flights, this research adds to the variability in refugee experience involving long and complex transit before resettlement in the US. One recent example is Hecht’s 2005 study of Sudanese refugee boys’ long journey to the US, starting with their escape from South Sudan to refugee camps along the country’s borders and in Kenya, followed by protracted waits before resettlement.3 Studying Chin refugees’ migration processes also clarifies social mechanisms that encourage cross-border movement despite restrictive policies and state authorities and shows how foreign historical connections allow for a ‘selectivity’ of certain groups over others when many have endured similar persecution. Put differently, it is vital to know who and what connections make refugee flows happen. Thus, this research complements understandings of refugee migration in its entirety, as much of the relevant research has been conducted in destination countries and refugee camps and focuses on policy issues, structural impediments and opportunities in rehabilitation processes, the adaptation and assimilation of refugee groups and settling services (Gold 1992; Ong 2003; Hein 2006; Brees 2010; Fiddian-Qasmiyeh 2011; Snyder 2011). Because the research focuses on receiving countries, little is known about the crucial role of faith-based organisations (FBOs) in refugees’ pre-departure circumstances. Horstmann (2011), Eby et al. (2011) and Nawyn (2006) have analysed the operations of FBOs in neo-liberal and post-neo-liberal societies, resource mobilisation by FBOs and the mechanisms of cooperation and constraint between the state and FBOs in changing the governance of refugee camps and asylum systems. But, studying how FBOs and secular organisations provide meaning and emotional support to Chin refugees in origin and transit countries clarifies how intermediate institutions and identifiable social forces pattern cross-border refugee flows. Refugee flows are, therefore, structured undertakings resulting from broad historical processes (Zolberg, Suhrke, and Aguayo 1989). In the subsequent section, I identify the theoretical framework used to analyse these cases, describe the study’s methodology and data and briefly review US refugee policies that created an enabling macro-environment that resonated with Burmese refugees’ personal aspirations. I then present several typical cases to illustrate the role of church and ethnic organisations and how religious affiliation and socio-economic status influence Chin families’ migratory decision-making and strategising for border-crossings to seek admission to the US as refugees or asylees. Finally, I examine the consequential role of Chin churches and other non-state actors in managing Chin refugees’ entry to the US.

Theoretical framework Examining Chin refugees’ motivations to migrate allows us to revisit migration theories with an emphasis on the context of exit. Multiple motivations cause migration, such as the push/pull thesis, the household strategy perspective and structural theories. In my view, the ‘culture of migration’ and differential access to social capital and networks provide the most suitable framework for analysing Chin refugees’ pre-departure decision-making process and migratory routes. The ‘culture of migration’ is the pervading cultural atmosphere in sending communities that promote migration. Ali (2007) defines it as ‘ideas, practices and cultural artefacts that reinforce the celebration of migration and migrants’, including ‘beliefs, desire, symbols, myths, education, celebrations of migration in various media, and material goods’ (39). 2 M. RAY

It is both a consequence of and complementary to sustaining cross-border migratory networks. In a study of Mexican migrants, Kandel and Massey (2002) highlight how migration becomes integral to local culture, fuelling further migration. Levitt and Lamba-Nieves (2011) argue that ‘social remittances’ (norms, practices, identities and social capital) migrants export to their sending communities through visits, letters, phone calls, emails and blogs reinforce the culture of migration until moving becomes inevitable for non-migrants because they are no longer content with their socio-economic prospects. Thus, where migration is prevalent it eventually becomes a normative community behaviour learned by observing dramatic improvement in migrants’ lives.

Migrant networks’ roles are well established (Boyd 1989; Koser 1997; Gold 2005; Bashi 2007; Poros 2011). Access, membership and participation in existing personal and social networks – that is, connections individuals make forming a web of relationships transmitting information about destinations and resources for settlement and secondary or return migration – typically influence migration decisions and processes. Thus, examining networks, especially family networks, allows for considering migration as a social product of macro and micro factors and as a collective process shaped by agency and structure (Gold 2005, 259; Bashi 2007). Network relationships are highly valued for the social capital and resources they bring to members. Social capital refers to a sense of commitment or mutual obligation that motivates people to extend favours, expect preferential treatment and look out for each other. Social capital strengthens the relationship from which it originates and its consumption usually increases rather than depletes its availability in a given context. However, social capital within networks can be distributed unequally. Some members will have greater access to it than others, and depending on members’ endowments, two networks might have equal levels of social capital but unequal access to resources (Gold 2002). For example, Poros’s(2011) research on the migratory networks of Gujarati Indians emphasises how network members’ dissimilar endowments of human, ethno-religious and organisational capital determine migratory routes and socio-economic mobility at their destinations. Bashi (2007) similarly observes an uneven distribution of resources and knowhow amid veteran migrants (hubs) and newcomers (spokes) from English-speaking Caribbean islands and the ways these links create an immigration network. While research on networks widely perceives them as positive, studies have also exposed their problematic features and negative consequences, such as excluding outsiders or potentially abusive informal regulations on members’ behaviour, as shown in Hondagneu-Sotelo’s(1994) study on Mexican domestic workers. Similarly, Menjivar’s(1997) research on Salvadorian immigrants in San Francisco reveals how migrant kinship support is contingent upon the host society’s reception of earlier migrants and how extreme and stressful situations can negatively affect network relationships. The network approach thus provides insight on how networks offer social support and resources to Chin migrants in various situations and how social inequalities affect Chins’ choices of migratory pathways for arriving as refugees or asylees on US shores.

Methods At the study site, a Midwestern city, an estimated 2500 Burmese refugees and asylees were resettled from 2001 to 2017. The majority are Chin, along with some Burman and Kachin JOURNAL OF ETHNIC AND MIGRATION STUDIES 3

Burmese (Burma Center 2017).4 My findings come from two data sources: two semi-structured focus group discussions with 55 Falam and 40 Hakha Chin refugees conducted at the Burma Center in July 2012 and 21 in-depth interviews with Chin refugee families in March 2013. The interviews included open- and close-ended questions concerning three major themes: (a) causes and local community structures or institutions that facilitated multi-stage migration; (b) respondent families’ utilisation of diverse networks; and (c) the cultural, human and financial capital that helped them control the perilous journey. Follow-up questions encouraged detailed descriptions of their pre-departure and migratory experiences. The Burma Center helped me identify 21 Chin families who arrived in America from 2001 to 2011, ranging in age from 24 to 56, using convenience and purposive sampling. This method ensured variation in the data by including extreme and typical cases and families with unlike socio-economic status, education, relationship with Burma’s military regime, age, refugee/asylee status and year of arrival. The organisation also arranged for a research assistant with adequate language proficiency in Burmese, English and ethnic languages. The research assistant, a Chin refugee, was a well-respected ESL teacher in the community. She assisted with translation and re-phrasing questions in a culturally sensitive manner to elicit accurate responses during interviews and focus group sessions. The interviews were conducted in participants’ homes in English, Hakha or Falam. Respondents with a high school education could communicate in English. All interviews and focus group sessions were recorded with the participants’ consent and transcribed verbatim in English. Names have been changed to protect identity. The data were analysed using inductive coding and the themes derived were grouped in four broad categories: physical/ psychological hardships; decision-making; resources and networks; journey and registration process.

The Burma Center’s staff presence at focus group sessions and the research assistant’s attendance during interviews helped me gain trust and helped the participants feel reassured enough to share information from their recent painful past. My identity as an immigrant woman from India also helped, as interviewees could relate with a sense of commonality because many of them or their family members spent time in India. The data also include conversations with Burmese church officials, representatives of international FBOs and voluntary organisations working with Chin refugees, and records and reports from nongovernmental organisations, UN agencies and the media on human rights abuses against Burmese ethnic minorities. This study does not capture the migratory experiences of all Burmese refugees admitted to the US; what I attempt to show are the interactions between broader forces and actions taken by Chin refugees and asylees at a particular time and place to ensure their safety.

Destination US The US has been the principal destination country for refugee resettlement since World War II. Although US refugee and resettlement policy has moral and humanitarian components, it has always been tied to political interests, and waves of refugees to the US have ebbed and flowed with global conflicts. From World War II to the mid-1980s, 90% of refugees resettled in the US came from former communist countries (including Hungary, Cuba, the former USSR, Vietnam, Laos and Cambodia) as the US government offered 4 M. RAY

refuge to those fleeing as a political strategy against communism (Haines 2010; Besteman 2016). The arrival of Indochinese and Soviet Jewish refugees peaked in 1980, precipitating the US Refugee Act of 1980, which currently dictates refugee admission. The act adopted the language of the 1951 Convention Relating to the Status of Refugees, which defines refugees as individuals with a ‘well-founded fear’ of persecution in their country due to race, religion, nationality, membership in a particular group or political opinion. It established the Office of Refugee Resettlement (ORR), raised refugee quotas, broadened the definition of a ‘refugee’ to include people from any country and allowed refugee status to be determined on ideologically, individually and geographically neutral standards.5 Another important aspect of US refugee admissions since World War II is the major role of FBOs and communities like the Church World Service (CWS), the Hebrew Immigrant Aid Society (HIAS), Lutheran Immigration Refugee Services (LIRS), the United States Conference of Catholic Bishops and non-sectarian organisations like the International Rescue Committee that mediated between the government and refugees. These organisations’ advocacy has been central to refugee admission and resettlement and has been crucial in defining refugees’ identity. Refugees with strong or multiple constituencies have done far better than refugees who have no sponsors by appealing to the right’s anticommunist sentiment, the left’s humanitarian sensitivity, or co-religionists’ and coethnics’ communitarian feelings (Haines 2010). For instance, the National Conference on Soviet Jewry and the Soviet Jewry Movement’s advocacy secured freedom of emigration for Soviet Jews (and others from non-market economies) when the US pressured the USSR with the Jackson-Vanik Amendment to the 1974 Foreign Trade Act. This amendment dramatically increased the number of Soviet Jewish refugees entering the US and is perceived as turning the tide in their freedom struggle (Goldberg 1996).

However, since 9/11 refugee admittance and resettlement programs have shifted dramatically to focus on heightened security concerns and enhanced screening. One change has been admitting smaller numbers of refugees from the most vulnerable populations rather than large-scale populations of interest to the US. This shift underscores the diversity of refugees’ regions and countries of origin, with the fastest-growing groups in 2016 coming from Near East/South Asian and African countries (US Department of State 2016). Of the 84,995 refugees admitted to the US in the fiscal year 2016, the largest numbers came from the Democratic Republic of Congo, Syria, Burma and Iraq (Igielnik and Krogstad 2017).

The context of exit: a nation of ethnic plurality and resistance Interethnic conflict has marked Burma’s history since pre-independence. Burma’s population of 56.8 million includes six main ethnic-linguistic minority groups – the Chin, Karen, Mon, Shan, Kachin and Rakhine – each with distinct traditions, languages, religions and degrees of autonomy from the Burman majority, who comprise 68–70% of the population (Rieffel 2010; CIA 2017). Burmans mostly practice Theravada Buddhism, reside in the country’s lowland centre and control the military and government, whereas ethnic minority groups inhabit mountainous regions along the country’s borders. The prominent ethnic minority groups – Karen, Kachin and Chin – are Christian (mostly Baptist) and comprise 4% of the population (Walton and Hayward 2014). JOURNAL OF ETHNIC AND MIGRATION STUDIES 5

The military-led government has persecuted ethnic minority groups since its inception in 1962. The government perceives non-Buddhist religious and ethnic differences as threats to Burma’s integrity and tools of regional and global power interests, and has thus severely limited religious freedom for minority populations. The policy of one people (Burman), one language (Burmese) and one religion (Buddhism) has been used to justify repressing ethnic religious minorities rather than assimilating them into the body politic (Walton and Hayward 2014). The Muslim Rohingya are the most systematically persecuted minority group. In 1977–1978 and 1991–1992, violence largely inflicted by government forces drove 450,000 Rohingyas out of Burma, an act resembling ethnic cleansing meant to permanently expel them (Fink 2009, 241). Rohingyas are denied citizenship under the 1982 Burmese Citizenship Act (Kipgen 2013, 300) and are confined to camps and villages where they must obtain permits to leave or seek healthcare. As a consequence of continual oppression, Burmese ethnic minority groups have asserted their quest for independent identity and religious freedom by engaging in violent insurgencies, which the military junta routinely and brutally suppresses in their attempts to assert Buddhist/Burman hegemony (Fink 2009). Widespread resentment towards military rule and police brutality climaxed in 1988s people’s revolution. Spearheaded by university students in Rangoon, it quickly spread nationwide, gaining support from various social and professional groups. Nevertheless, it was unsuccessful for lack of national leadership and acumen in establishing a new administration and also because of non-participation by ethnic armed organisations. Minority leaders felt it was not their struggle, perceiving the movement as a battle between Burmans. The military responded violently, killing an estimated 3000 people and imprisoning many more (Fink 2009; Human Rights Watch 2009). The regime regained control and brought new military leaders, the State Law and Order Restoration Council (SLORC), to power. The SLORC announced that elections would be held in May 1990, but the results were nullified and military rule continued until recently, changing only in name to the State Peace and Development Council (SPDC) in 1997 (Rieffel 2010).6

By the mid-to-late 1990s, the regime faced a weakening economy, rising inflation, declining foreign investment and pressures from domestic political groups and foreign governments and organisations. This led to both legal and irregular emigration from urban and rural areas to seek work outside Burma and escape forced labour in ethnic states (Hlaing 2010). Hence, the migration streams included majority and ethnic minority Burmese comprising of highly and semi-skilled professionals, entrepreneurs, church officials, students, activists, farmers and labourers seeking safety and better options, similar to previous Cuban, Vietnamese and Soviet Jewish refugee populations. Notably, for Chins escape seemed likely only when the US agreed to grant refugee status to Burmese nationals and when intermediate actors – FBOs and smugglers – intervened between refugees and the national and international institutions impacting their futures.

Triggers for migration The central presence of faith in the Chin community is key to understanding their motivations for migration. Being Christian is intrinsically linked to the reasons for Chins’ exodus, an aspect less emphasised by refugee scholars compared to religious beliefs and religious charities’ role in providing aid or resettlement (see Eby et al. 2011; Fiddian6 M. RAY

Qasmiyeh 2011; Horstmann 2011). The American Baptist Church’s missionary work among the Chins dates to the 1800s and has influenced their religious and ethnic identity, which distinguishes them from the Buddhist Burmans. Like Karens and Kachins, most Chins are Protestants and support American missionaries. Though the Chin community is exceedingly ethnically diverse,7 Chins identify with a common history, homeland and faith.

During years of military oppression, local pastors and church networks provided economic and emotional support, security and social recognition and organisation to the Chin community. Chin churches nourished members’ thoughts of an imagined community and their aspirations for escaping economic anxieties and human rights abuses. Church membership also enabled Chins to build ties with co-ethnics through international networks. Elaborating on this ‘transcendent motivation’, the reverend of First Baptist Church, part of the Burmese Christian Association of North America, stated:

The Chins understand their suffering and plight by drawing parallels to Israelites’ enslavement in Egypt and their exodus story ... they compare themselves to the Israelites who had to go through many plights on their way to the Promised Land. For the Chins, their faith is their power of imagination and articulation of a deeper meaning of ‘life’ in process. Thus, faith offered respondents an alternative vision of their predicament and powerful motivation to strive for ‘what life should be’ (Snyder 2011, 574). At the intermediary level, American Baptist churches, with their broad geographical networks, pursued a unified strategy for lobbying the US Department of State and Homeland Security, Congress and the UNHCR to offer resettlement to Karen and Chin refugees on grounds of religious persecution. Responding to local churches’ requests and as a partner of the CWS, American Baptist churches created the Burmese Task Force in 2007 to seek funding for refugees and build support networks among congregations (ABCOPAD 2016). I argue that Baptist church organisations acted as mediators helping Chin migrants navigate both the official entry process to the US and ‘the unknown seas to their countries of destination, and for states to bridge principles which cannot be reconciled on a practical level’ (Faist 2014, 43).

In many respects, Chin refugees’ experiences are analogous to those of Soviet Jews who left the USSR in the 1970s with support from the American Jewish Joint Distribution Committee and HIAS – both Jewish humanitarian assistance organisations tied to the Council of Jewish Federations, the most powerful American Jewish lobby that campaigned for the Jackson Amendment (Tress 1991; Goldberg 1996). So, being ‘Christian’, for Chin migrants, is linked with US refugee law provisions that provide plausible claim to refugee status. The Department of State has listed Burma a Country of Particular Concern under the International Religious Freedom Act of 1998 (US Department of State 2016, 34–35) for persecuting religious minorities, and Burmese refugees had access to family reunification processing through Priority 3 until 2016. Besides upholding migration as an ideal for Chins, the churches also imparted in them a lack of fear of international migration. Consequently, plans to escape Burma were not isolated decisions pursued by individuals but consensual decisions involving families and communal contacts.8 The respondents shared numerous reasons for escaping Burma, as shown in Figure 1. No one reason took priority, but flight strategies and pathways to safety and resettlement evolved as different escape opportunities became available. JOURNAL OF ETHNIC AND MIGRATION STUDIES 7

Sometimes, migration was precipitated by life-changing incidents, like the abduction of a family’s sole provider or the timely mobilisation of social and financial resources for the journey. This meant Chin families rarely left Burma as a single unit: parents and grandparents joined adult children and vice versa, or close/distant relatives and church members travelled together. The success stories of those who made it to the US or Malaysia in the process of being approved for refugee status by the UNHCR enhanced the desire for migration. Social remittances in the form of tales of lives without extortion and military harassment shared through phone calls, emails, visits and social media created expectations that Chins could emigrate to the West to fulfil essential needs like healthcare, education, housing and food security. ‘Just to have equal opportunity because I heard there is no high and low class for basic necessities; I wanted to go’, said Jane, a farmer and mother of four. ‘One thing migration has brought with it, is the ability for us to choose who you want to be, what kind of life you want ... not to fear my identity’. Departing as a refugee thus became a status marker (Kandel and Massey 2002; Ali 2007), especially for younger Chins, though some perceived lower risks in their present circumstances. Though the culture of migration was pervasive throughout the Chin community regardless of class or social status, better-off families had more latitude in strategising the timing of departure, as described by Roselyn, daughter of a businessman whose enterprise was targeted by the military because of his faith.

My dad ... encouraged us to go to America after I finished school. I was ready to go even on my own ... because when my family came back to Burma in 1992 from US for a visit ... I see the difference of my and their life, and what they tell me about America. I was always dreaming of coming to America.

Participants firmly perceived ‘migration’ as an act of self-actualisation and social mobility. The flows of financial remittances in and around respondents’ homes were also powerful incentives to leave Burma.

Choosing among alternatives for resource-poor chins Participants from six of the 15 resource-poor families in this study who were principal migrants or joining their families mentioned the assistance and influence of pastors and close friends from church, immediate family members’ work experiences in India or Thailand and the role of smugglers in their migratory strategising. Men in poor families were familiar with smugglers’ fees, Thai and Malaysian border soldiers’ militarised policing and numerous routes from previous border-crossing experiences. This first-hand information fed into the decision-making process, as Robert, father of four and sole provider for his family, recounted: I was a driver in Mizoram and CNF [Chin National Front]9 hired me to carry rice, letters, and food for this student group. It was a risky job, and I feared for my life. I returned to my family in Falam. I started driving for an army general but they suspected I used to be a driver for this banned student group. I was imprisoned and tortured by the military several times. I decided ... before I die, let me escape to Malaysia with my wife and youngest child. As Koser (1997) mentions, smugglers (referred to as ‘agents’ by interviewees) were a vital information source for strategising escape plans. Easy access to smugglers within the community significantly facilitated flight. Respondents also described the benevolent public face of smugglers’ operations in their communities. Underprivileged Chin refugees were impressed by smugglers’ ingenuity, adaptability and determination in the face of harsh penalties, as Robert stated: ‘I have known the smuggler and their operation for a long time ... without doubt he knows plenty’. As Townsend and Oomen (2015) observe, analysis of family and friends’ approval of smugglers’ services, despite their image of criminality, is missing in refugee literature. Poor Chin families did not dwell upon the legality of using smugglers, so there was no contradiction between the smugglers’ profit-orientation and the trust migrants and their families had in them (Faist 2014). Poor Chin families, particularly from rural areas, revealed how the constant presence of soldiers demanding forced labour negatively impacted their families and communities. For indigent families, losing a labourer for days had serious financial consequences. Many wives or older children who entered into forced labour were sexually assaulted or beaten. The most common forms of forced labour were carrying military supplies or working as a human minesweeper, which often resulted in injury or death with no compensation. Many hamlets in Chin State were destroyed or forcibly depopulated by military regimes (Fink 2009). Stephen, a small farmer, experienced repeated victimisation by the military before escaping:

I escaped from the camp with help from the security guard, who finally took pity on my misfortune ... While crossing the border I was caught by the Thai border police and held in the detention centre. My family knew nothing [of] what happened to me. My Church bailed me out ... the UNHCR came to centre and registered me as an asylum seeker before I had reached Malaysia ... the church took care of me and with money from friends, my wife and children came after a year.

Protection, support and institutional assistance from churches and ethnic communitybased organisations (CBOs) compensated for poor Chin families’ lack of capital and emboldened them to migrate irregularly. In nine cases, migration decisions were consequences of modifications in UNHCR policy or US visa waiver policies. Awareness of policy changes was a major determining JOURNAL OF ETHNIC AND MIGRATION STUDIES 9

factor in deciding who departed as a family’s principal migrant. In the following extracts, Mary, a 26-year-old woman, and Rita, mother of a 14-year-old son, explain their families’ decision-making and show the selectivity of sex, age and finances in the process. Mary’s motivation was the special quotas for pregnant women in the UNHCR’s refugee registration policies:

My brother-in-law, who was in Malaysia, called his brother [my husband] to find out if I was pregnant, because UNHCR was prioritising pregnant women’s applications for refugee status. I was two and a half months pregnant with my daughter ... we sold our property and used that money for travel cost[s] ...

For Rita’s family, the chance to end forced labour came when the UNHCR’s policy prioritised registration for minor Chin migrants and unaccompanied children: My family was forced to work to build the Buddhist pagoda. They [military] don’t pay us and they don’t feed us, so it is very hard to survive. My husband had a broken leg ... so the military abducted my oldest son for forced labour ... after that with agent’s help he [the son] fled to Malaysia.

The power of chance for resourceful chins Dan, a 56-year-old former school teacher, described what he considered an American policy loophole that informed affluent Chin families’ decisions. From June 2000 to January 2001, Burmese citizens could travel to Guam on the ‘Guam-Only Visa Waiver Program’ (GOVWP) for a 15-day period.10 While this was not the regular escape route for Chin migrants, six families in this study could take advantage of this opportunity to seek political asylum in Guam because of their class privilege. Though risky, it was a creative and effective use of intellectual, cultural and financial resources. Close-knit interpersonal trust networks (Tilly 2007) played a key role in these families’ journeys to Guam. This group included professionals, academics, political activists, students and church/ community leaders who resisted the military regime and were persecuted by the Burmese government. Members of this network enjoyed a ‘trust’ relationship of strong transnational ties that enabled them to facilitate their comrades’ escape to the US via Guam. This network exemplified the ‘solidarity between people at the origins and destinations of migration streams’ (Tilly 2007, 5), as Dan recollected:

My family and I have suffered for a very long time from 1988 till I left in 2000. I had to escape to Rangoon for safety and moved my family to my in-laws home. I heard of Visit Guam Year from the BBC. My friends in the US insisted I leave ... it was practical concerns that determined the directions of my life from then on.

Similarly, Roselyn described leaving her family: When I had this opportunity, my dad said to my brother, “too many things going on with this military government, why don’t you and your sister go together so you can take care of each other”... so we left with five other folks. The participants also indicated that Chin families’ social and financial status did not immunise them from abuses by the military, particularly in villages earmarked as ‘areas of armed resistance’. If anyone was suspected of giving information or assistance to the ethnic resistance army, the whole village was punished. Chin families from such villages 10 M. RAY

were caught between the demands of Burmese soldiers and ethnic armies. Melanie recalled the horrific circumstances that compelled her husband to escape: My husband was the headman, who was contacted by members of CNF at a gunpoint for money. He didn’t have the money, so he asked the school accountant to give it to CNF members or face death. The school principal was so angry, he made a complaint to the government in Rangoon ... they arrested my husband and tortured him. After that it is not safe for him to live in the village. He called his family in America and told them he needed to get to Guam. They helped him with his travel documents and costs. I came later with six children. It was not uncommon for family members to arrive in the US using different pathways during the same or different timeframes, especially after visa-free travel was suspended in January 2011. Chin families with social and financial power considered this singular opportunity to flee Burma as a shorter and highly probable route to reach America.

Desperate journeys Due to complicated procedures that deter Burmese – especially the poor – from leaving legally (Mon 2010), 15 families in this study were compelled to enter Malaysia as irregular migrants in anticipation of gaining refugee status before moving to the US or another industrialised country. Although Burmese ethnic minorities share the same fears of persecution, numerous considerations influence their preferences for safe locations. Rohingyas mostly escape to refugee camps at the border or in Bangladesh and Malaysia in hope of better treatment in Muslim countries, whereas most Karens live in and outside refugee camps along the Thai-Burma border (Brees 2010; Cheung 2012). Chins have primarily sought refuge in Malaysia and India. Normally, they have no refugee camp experience, so unlike other minority groups they face challenges navigating Malaysia’s highly restrictive immigration policies in urban settings (Mon 2010; IRC 2012). My conversations with resource-poor migrants gave insight into two irregular routes to Malaysia’s porous borders via Thailand. One was from Chin State to Yangon, then to Kawthaung in Burma’s southernmost tip to enter Thailand at Ranong before entering Malaysia. The other was from Tachileik to Mae Sai in northern Thailand, then to Kuala Lumpur in Malaysia. This meant the respondents had to cross two international borders, which was achieved through a series of interconnected networks of smugglers – Burmese, Thai, Indonesian or Malay men – who helped them to reach Kuala Lumpur. Migrants were instructed to prepare emotionally for their perilous journey, which typically lasted two weeks, and to carry minimal provisions due to lack of space in the vehicle, which was a small car or van, a fishing boat, a two-wheeler or even a bicycle. Maria described the vulnerability and resilience of migrants trying to reach Malaysia:

We were packed like farm animals ... like pigs and chickens in a small car. There were fourteen of us, and some were packed tight in the trunk of the car. We travelled in many vehicles ... but in many places we just walked very long distances in the dark through thick forests and swamps ... parents had to carry their children. [At some point] we crossed a river by boat. The men swam across the river ... we did not speak to each other or to the agent because he spoke Thai. We followed him and then he was gone ... another agent took us to Kuala Lumpur.

JOURNAL OF ETHNIC AND MIGRATION STUDIES 11

Travelling in unobtrusive vehicles that could easily hide amidst bigger vehicles at checkpoints, staying in decrepit ‘drop’ houses by day and travelling only after nightfall and frequently changing smugglers were strategies to avoid detection at border-crossing points. Some respondents’ journeys were prolonged due to weather, heightened border policing, vehicle breakdown or unavailability of a vehicle, driver or both. Interviewees witnessed deaths of children and adults when boats capsized or due to total exhaustion, bribery of border officials, injury, robbery, physical abuse by soldiers and threats of sexual abuse and refoulement from immigration police. Upon reaching Kuala Lumpur, the migrants met their friends, church members, pastors or family. Some continued to the Klang Valley, Penang or Johor Bahru. The average cost to reach Malaysia was US $600–700 per person, which was raised by selling or pawning farmland, tools, livestock and other assets or through funds from American Baptist Churches, family and friends.

The norm for Chin migrants who travelled to Guam in 2000 was to hire a broker familiar with payoffs and protocols for obtaining passports and visas from Burmese government officials for US $750 per passport. Some participants hid their identity to avoid detection by the Burmese Military Intelligence and lived incognito in friends’ or relatives’ homes in Rangoon. The Chins arrived in Guam as tourists through Bangkok via Seoul, Manila or Taipei. Plane tickets cost $1000 and they brought $500 with them as ‘show money’. Within 15 days of their arrival, respondents with the GOVWP visa submitted their political asylum applications to the US Immigration and Naturalization Service (INS) asylum office in California on grounds of religious persecution and torture in Burma. The CWS helped later arrivals of Burmese migrants, as explained in the next section.

Between worlds: navigating Guam and Malaysia’s inhospitable spaces As a process, ‘transit’ migration cannot be examined outside the context of restrictive migration and asylum control policies. Dimitriadi (2013) states that a confluence of factors encourages transit migration: structural obstacles like border control policies, employment opportunities in transit countries, expenses for the journey and the presence and/or development of social capital.11 Chin families perceived their transit as irregular migrants in Malaysia as integral to their journey.

Malaysia has a long history of providing temporary asylum to refugees and asylumseekers, including Cambodian and Vietnamese refugees in the late 1980s–1990s, some Bosnian refugees in the early 1990s and Indonesians in early 2000 (Equal Rights Trust 2014). Currently, Malaysia hosts one of the largest urban refugee populations. In February 2016, Malaysia’s UNHCR had 158,510 registered refugees and asylum-seekers, according to its website; 90% were from Burma. Chins and Rohingya constituted the largest ethnic groups. Since the 1970s globalised structural forces have transformed Malaysia into a newly industrialised market economy. The government thus allowed large-scale recruitment of migrant workers from neighbouring countries, including Burma (Nah 2014). The main ‘pull factors’ for migrants from Southeast Asia and Burma arriving in Malaysia are (a) work opportunities; (b) the UNHCR’s presence for regulating refugee affairs; and (c) access to social capital and support from Chin Baptist churches and communities. Malaysia, therefore, is both a destination and transit country for Southeast Asian migrants. 12 M. RAY

Transit migrants in Malaysia Economic opportunities and the UNHCR’s presence in Malaysia created both a supportive and vulnerable environment for Chin migrant families in transit. Six CBOs servicing the Chin refugee community helped pool resources, find work and accommodations, provide migration-related information, assist with asylum application and interviews and intervene when Chin migrants were arrested and detained. Parallels can be drawn between the experiences of Chins and Jewish migrants who left the USSR for Vienna with Israeli visas in the late 1980s and received help from HIAS staff for their US visa applications. HIAS arranged for most Jewish migrants to be classified as ‘refugees’, circumventing the quota system and making the State Department’s Bureau of Refugee Affairs responsible for them (Tress 1991; Goldberg 1996). Likewise, Chin CBOs and Baptist churches helped destitute Chin families enter the US as refugees. The UNHCR and Chin church communities in resettlement countries were major funding sources for CBOs, together with negligible annual membership fees paid by transit migrants (Floyd, Zeller, and Abbott 2015). In contrast, a lack of ethno-religious organisational capital has left Malaysia’s UNHCR to pursue local integration as the most durable solution for resettling Rohingya Muslims since 2000, though this solution was recently abandoned. Rohingyas’ religious identity and resettlement countries’ unwillingness to accept Muslim refugees after 9/11 take precedence in UNHCR practices and policies, which is perceived as controversial, given the spirit of the Geneva Convention (Equal Rights Trust 2014).

Largely, the respondents in the study arrived in Malaysia with no easily transferable skill-sets and little human capital, which channelled them into unskilled, low-paying jobs. They found employment through church, town or family networks. But, they continued to feel unsafe, as Malaysia is not part of the 1951 Refugee Convention and its government considers refugees, asylum-seekers and stateless persons as irregular immigrants under its 1959/1963 immigration law (Cheung 2012; Nah 2014). As in other countries in the region, policies regarding refugees and asylum-seekers focus more on border control, removal and deterrence than protection. Registering and receiving refugee status from the UNHCR was a lengthy and difficult process, averaging three to four years, several interviews, biometric tests and tireless preparation and interventions from CBO staff. Rose, who arrived in the US as a refugee in 2009, worked for Malaysia’s UNHCR office and had first-hand knowledge of the registration process. She stated:

No one could directly approach the UNHCR at KL for asylum registration, except those who belonged to UNHCR designated group like minor, pregnant woman, or with vulnerable medical condition. All others had to wait for ‘site registration’ by UNHCR staff, like at a school in localities with high density of Chin migrants, or in the jungle camps outside KL, jail etc. There was no fixed timetable for UNHCR ‘mobile/site registration’. The CBOs prepared the asylum application explaining migrants’ reasons for seeking asylum along with biographic documentations. The selection process is very strict and to some extent random. Applicants who were strong cases for resettlement moved forward. Successful applicants at this stage were given RSD (Refugee status determination) status by UNHCR. It was a time of very high anxiety for Chin folks, because of high volume of rejection. UNHCR registration provides migrants with a few benefits, including discounted medical treatment and some protection from arrest and deportation while in Malaysia. The next JOURNAL OF ETHNIC AND MIGRATION STUDIES 13

stage was screening and interviews by the Overseas Processing Entity that prepared individual refugee cases prior to interviews with the Department of Homeland Security’s United States Citizenship and Immigration Services (DHS/USCIS). As an interpreter at this crucial stage, Rose recalled:

These interviews conducted by USCIS officers were the toughest ... where I witnessed resilient Chin men/women who had withstood life-threatening torture get nervous. DHS officers have the power to approve/disapprove refugee applications. It was intimidating for migrants as they had to convince the official of their suffering and persecution, in a language they did not often understand. Many had difficulty in articulating their narration due to psychological trauma or having their children with them listening. Sometimes, rejections happened because of misunderstanding cultural aspects or misrepresentation by the interpreter. After being cleared by the DHS/USCIS, the migrants underwent medical examination and cultural orientation classes and finally received travel documents from the International Organization of Migration. The respondents mentioned experiencing threats to personal security, detention and deportation throughout the registration process. Their lack of Malaysian language skills and ignorance of their rights made them victims of extortion, robbery and harassment from police and frequent raids by RELA officers (the People’s Volunteer Corps, with the power to stop, search and arrest anyone suspected of being an ‘irregular migrant’). To avoid scrutiny, Chin women sought employment in ethnic restaurants, where they could bring their young children to work and have access to leftover food. Younger Chin couples preferred working at the same restaurant, as it minimised workplace and sexual abuse, which was common. They routinely experienced verbal abuse, on-the-job injury, non-payment or partial payment of wages and dismissal without reason, but this work was important as many participants stated they felt obligated to send remittances to their families in Burma for survival and to settle debts. For the 15 resource-poor families, the main factors determining their preferences for resettlement countries (the US, Canada, Australia) were the presence of church members, pastors and village/town friends and the prospect of family reunions, as they expected support on arrival. However, the UNHCR made the final decision in consultation with receiving countries’ governments.

As tourists in Guam Chin migrants who entered Guam as tourists in 2000 were welcomed and received support from local Chin churches and the resident Chin community, who provided housing and amenities like blankets, clothing, beds, cooking utensils, money and food. Chin migrants formed the ‘Burmese Christian Fellowship’ with a local Baptist minister as its leader to nurture Chin interests and create a sense of community identity (Tilly 2007). But due to large numbers of arrivals from Burma and other countries, 15 days was rarely enough time for processing applications or conducting the credible-fear interviews. The CWS offered to provide legal assistance and act as interpreters to expedite applications, but since November 2000 the INS has required that asylum seekers without proper documentation must be held in custody during the asylum process. As a result, hundreds of asylum seekers – including 325 Burmese from various ethnicities – were detained. The US suspended the GOVWP for Burmese citizens on 10 January 2001 (Human Rights Watch 2001). 14 M. RAY

The respondents vividly remembered the detention experience: women were housed in the Agana lockup alongside violent criminals without adequate bedding or hygienic items, whereas the 300 men were held in tents outside the Department of Corrections (DOC) facility without protection from weather or mosquitoes, with unhygienic conditions and little food or clean drinking water. With help from CWS lawyers and interventions from international bodies like Human Rights Watch and the American Civil Liberties Union, and following extensive media coverage, about 90 detainees were ‘paroled’ without a hearing. In April 2001 the INS decided to release the remaining 230 asylum seekers to the CWS until their cases could be determined by an immigration judge (Human Rights Watch 2001). During this time, the CWS mobilised support networks among American churches and requested members on the US mainland to sponsor refugee families or provide employment, as recounted by Roselyn and Dan, respectively: After we got parole from the camp, my brother got a job in Texas, and he moved out. A pastor’s family provided housing and food for me, and in return I cleaned the house and babysat for them. In 2004, I won my case for asylum. After six years of waiting on parole, where we could not work ... my family joined me in

Guam. I lost so many years of my life doing nothing but taking leadership of my community ... helping others as a translator when church and legal groups came from mainland

America to help us out. But without their help ... we could not have made [it] out of the camp.

The CWS provided continuous support, demonstrating how an intermediary organisation can help resourceful Chin migrants achieve safety in ways individuals could never accomplish alone. By offering assistance during this process through their own resources, social networks – particularly American Protestant congregations – shaped Chin refugees’ socio-economic adaptation, identities, incorporation and religious practices in meaningful ways (Nawyn 2006; Eby et al. 2011). Thus, religion can facilitate assimilation, as it fosters group solidarity and a sense of belonging in the receiving society (Fiddian-Qasmiyeh 2011). With respect to Burmese migrants, the convergence of ethno-religious interests between the US and American Protestant churches has led to the successful admittance of Chin refugees, leaving the Rohingya with few options.

Conclusion In concluding her 2009 TED Talk ‘The danger of a single story’, Nigerian author Adichie insisted ‘nobody is just a refugee’. Looking closely at Chin families’ migratory strategies lends credence to this idea, showing the pre-migratory agency of an extremely heterogeneous group. From an empirical perspective, the narratives revealed varied motivation among Burmese seeking refugee admittance to the US, challenging the prevailing notion of a politically inert refugee population needing international rescue. The ‘culture of migration’ perspective has proven effective in clarifying migration decisions made by some Chin families. Rather than viewing them in a simple narrative of displacement as abused and victimised individuals – an image refugees must project to secure support – I find they act like agents taking charge of their lives through complex flight strategies. Although escape may have originally been prompted by victimisation, the trajectory the Chins charted showed significant ingenuity, deliberation and resilience. Further, JOURNAL OF ETHNIC AND MIGRATION STUDIES 15

my study indicates that ‘transit countries’ should not be simplistically seen merely as

transit places. Chin migrants were integrated into host countries’ underground economies, taking jobs native citizens did not want while simultaneously remaining marginalised. So, Chin migratory movements must be placed within local sending contexts and

should consider macro conditions – like the presence of American churches and their ties to US national interests – while acknowledging meso-level actors that mediate the refugee regime to ease migration. Finally, in addition to explaining Chin refugees’ motivations and transit pathways, I have highlighted disparities within the Chin community, which manifest in how financial,

cultural and social capital is acquired through faith networks. These factors shape specific migratory routes and the level of success Chin families have navigating legal immigration structures at refugee receiving countries. Given shifting policies regarding refugees from Burma across several resettlement countries, the situation in Burma needs close monitoring. The recent election of a democratic government under Aung San Suu Kyi does not eliminate fears for minority communities. Continued violence toward the Rohingya implies that forced migration will continue

unless serious political commitments address issues of equitable access to public goods, respect for religious and ethnic freedom and institutional inclusion of minorities.

Notes 1. Since the 1990s, Karen, Chin, Karenni refugees and smaller numbers of Shan, Mon and

Rakhine fled Burma (mostly to Thailand, Malaysia, Bangladesh and India) from government army offenses. An estimated 120,000 live in UNHCR camps in Thailand and around

130,000 Burmese reside in Malaysia. Since 2005, the UNHCR’s resettlement program has sent Burmese refugees to the US, Canada and Australia (Rieffel 2010; Cheung 2012; CIA

2017). 2. The concept ‘context of exit’ introduced by Portes and Rumbaut (2006) captures the sending countries’ context, encompassing home countries’ policies, political/economic situations and demographic and physical features (e.g. proximity between sending and receiving country) shaping the type of migrants arriving in receiving countries (79–86). I have slightly altered this definition for this research. 3. Similar examples can be found in 2016 news reports on Syrian refugees’ experiences crossing from Greece to Eastern Europe to Western European countries like Austria, Germany and Sweden. 4. Approximately 113,000 Burmese refugees live in the US (see Zong and Batalova 2015). Texas has the largest population, followed by New York, Indiana and Michigan. 5. In the US, refugees and asylees both possess a ‘well-founded fear’ of persecution and seek international protection. They are defined by their geographical location: refugees are those seeking protection who are situated outside their home country and the US and who apply via the US Refugee Admissions Program. Asylees are persons in the US seeking protection. If granted asylum by DHS/USCIS, they have the same rights as refugees (Zong and Batalova 2015). 6. With increased calls for political reforms by the international community and domestic opposition, SLORC implemented a new 2008 Constitution. It held elections in 2010 to form a

quasi-civilian government led mostly by ex-military officers from the SPDC’s political wing, the Union Solidarity and Development Party. To bring political and economic reforms, the government legalised trade unions, released political prisoners, signed ceasefire agreements

with ethnic insurgent groups and relaxed media censorship. With growing political participation, elections were held in 2015 that resulted in victory for Aung San Suu Kyi’s opposition

16 M. RAY

party, the National League for Democracy. Thus, her government has the opportunity (though sharing power with the military) to resolve lingering conflicts with ethnic minority groups (CIA 2017). 7. More than 45 dialectic groups identify as ‘Chin’, including the Falam, Hakha, Matu, Mizo and Zomi. 8. From 2000 on, Chins perceived the US and Australia as safe resettlement options. As Southeast Asian states are not signatories to the 1951 Geneva Convention on Refugees

(besides Cambodia and the Philippines), they tend to treat refugees crossing their international borders as irregular migrants subject to detention and deportation. Similarly, the

US rejected the UNHCR appeal urging Western countries to grant temporary asylum to refugees (Dimitriadi 2013). Thus, refugee admittance has become highly political and selective; only 1% of the total refugee population typically achieves formal resettlement (Fiddian-Qasmiyeh 2011). 9. Founded in 1988 with headquarters in Mizoram (India), the CNF is an insurgent group seeking self-determination for Chins (Fink 2009). The CNF and its armed wing, the Chin

National Army, draw much public support, leading to widespread harassment and victimisation among civilians in Chin State who endure the consequences of the violent struggle

between CNF insurgents and Burmese government forces. 10. The GOVWP admits aliens into Guam as non-immigrant visitors for business or pleasure for up to 15 days, visa-free, upon meeting certain conditions. In 2000, 480 Burmese citizens were permitted entry into Guam. The number of non-immigrants who applied for asylum increased significantly from 63 in 1999 to 251 in 2000. In December 2000, 169 non-immigrants, nearly all citizens of Burma who entered under the GOVWP, applied for asylum. In order to ensure the program’s security and preserve its integrity, Burma was removed from the eligible country list. See Department of Justice regulation in Federal Register 66:7 (10 January 2001) http://www.gpo.gov/fdsys/pkg/FR-2001-01-10/html/01-700.htm. 11. See Collyer and de Haas (2012) and Schapendonk (2012) on developing the concept of transit migration as part of mobility patterns and ‘trajectories’. See Collyer, Duevell, and de Haas (2012) on conceptualising transit migrants, including their intentions to further migrate and the extent to which they feel constrained in leaving the transit country by lack of resources, and classifying migrants accordingly (e.g. EU-bound or stranded migrants).

Disclosure statement No potential conflict of interest was reported by the author.

References ABCOPAD (American Baptist Churches of Pennsylvania and Delaware). 2016. “Burma Task Force Updates.” Accessed March 5. http://www.abcopad.org. Ali, S. 2007. “‘Go West Young Man’: The Culture of Migration among Muslims in Hyderabad, India.” Journal of Ethnic and Migration Studies 33 (1): 37–58. Bashi, V. 2007. Survival of the Knitted: Immigrant Social Networks in a Stratified World. Palo Alto, CA: Stanford University Press. Besteman, C. 2016. Making Refuge: Somali Bantu Refugees and Lewiston, Maine. Durham, NC: Duke University Press. Boyd, M. 1989. “Family and Personal Networks in International Migration: Recent Developments and New Agendas.” International Migration Review 23 (3): 638–670. Brees, I. 2010. “Refugees and Transnationalism on the Thai-Burmese Border.” Global Networks 10 (2): 282–299. Burma Center. 2017. http://www.burmacenterbc.org.

JOURNAL OF ETHNIC AND MIGRATION STUDIES 17

Cheung, S. 2012. “Migration Control and the Solutions Impasse in South and Southeast Asia: Implications from the Rohingya Experience.” Journal of Refugee Studies 25 (1): 50–70. CIA (Central Intelligence Agency). 2017. “Burma.” The World Factbook. Accessed February 5. https://www.cia.gov/library/publications/the-world-factbook/geos/bm.html. Collyer, M., and H. de Haas. 2012. “Developing Dynamic Categorisations of Transit Migration.” Population, Space and Place 18 (4): 468–481. Collyer, M., F. Duevell, and H. de Haas. 2012. “Critical Approaches to Transit Migration.” Population, Space and Place 18 (4): 407–414.

Dimitriadi, A. 2013. “Transit Migration to Greece: The Case of Afghans, Bangladeshis, and Pakistanis.” Working paper No. 71. Hellenic Foundation for European and Foreign Policy (ELIAMEP), Migration, Athens. Eby, J., E. Igarashi, L. Agadjanian, and D. Grace. 2011. “Faith-based Organizations and Private Sponsorship of Refugees in the United States.” Journal of Refugee Studies 24 (3): 586–605.

Equal Rights Trust. 2014. Equal Only in Name: The Human Rights of Stateless Rohingya in Malaysia. The Equal Rights Trust, London, in partnership with The Institute of Human Rights and Peace Studies, Mahidol University and The Tenaganita Women’s Force. Faist, T. 2014. “Brokerage in Cross-border Mobility: Social Mechanisms and the (re)production of Social Inequalities.” Social Inclusion 2 (4): 38–52.

Fiddian-Qasmiyeh, E. 2011. “Introduction: Faith-based Humanitarianism in Contexts of Forced Displacement.” Journal of Refugee Studies 24 (3): 429–439.

Fink, C. 2009. Living Silence: Burma under Military Rule. London: Zed Books. Floyd, A., M. Zeller, and L. Abbott. 2015. “A Case Study of Non-government Organizational Support in Myanmar Migrant Education.” Journal of Education and Learning 4 (4): 39–53. Gold, S. 1992. Refugee Communities: A Comparative Field Study. Newbury Park, CA: Sage. Gold, S. 2002. The Israeli Diaspora. London: Routledge. Gold, S. 2005. “Migrant Networks: A Summary and Critique of Relational Approaches to International Migration.” In The Blackwell Companion to Social Inequalities, edited by M. Romero and E. Margolis, 257–285. Malden, MA: Blackwell Publishing. Goldberg, D. 1996. To the Promised Land: A History of Government and Politics. New Brunswick: Rutgers University Press. Haines, D. 2010. Safe Haven? A History of Refugees in America. Sterling, VA: Kumarian Press. Hecht, T. 2005. Lost Boys of Sudan. Center for Applied Linguistics, Washington, DC. http://www. culturalorientation.net/learning/backgrounders.

Hein, J. 2006. Ethnic Origins: The Adaptation of Cambodian and Hmong Refugees in Four American Cities. New York: Russell Sage Foundation. Hlaing, K. 2010. “Introduction: Civil Society in Burma.” In Civil Society and Religion in Burma, edited by K. Hlaing, U. Nwe, Y. Tuns, T. Oo, and U. Than, 28–52. Dictionary of Asia Pacific Migration, ISEAS (Institute of Southeast Asian Studies) Publishing, Singapore. Hondagneu-Sotelo, P. 1994. “Regulating the Unregulated? Domestic Workers’ Social Networks.” Social Problems 41 (1): 50–64. Horstmann, A. 2011. “Ethical Dilemmas and Identifications of Faith-based Humanitarian

Organizations in the Karen Refugee Crisis.” Journal of Refugee Studies 24 (3): 513– 532. Human Rights Watch. 2001. United States: Locked Away: The Asylum Seekers of Guam, October 24, New York. Human Rights Watch. 2009. We Are Like Forgotten People. HRW Report. https://www.hrw.org/ report/2009/01/27/we-are-forgotten-people/chin-people-burma-unsafe-burma-unprotectedindia. Igielnik, R., and J. Krogstad. 2017. Where Refugees to the US Come From. Washington, DC: Pew Research Center. International Rescue Committee. 2012. “Resettlement Statistics 2002-2012.” http://www.rescue.org/ page/resettlement-statistics-2002-2012.

18 M. RAY

Kandel, W., and D. Massey. 2002. “The Culture of Migration in Mexico.” Social Forces 80 (3): 981– 1004. Kipgen, N. 2013. “Conflict in Rakhine State in Myanmar: Rohingya Muslims’ Conundrum.” Journal of Muslim Minority Affairs 33 (2): 298–310. Koser, K. 1997. “Social Networks and the Asylum Cycle: The Case of Iranians in the Netherlands.” International Migration Review 31 (3): 591–611. Levitt, P., and D. Lamba-Nieves. 2011. “Social Remittances Revisited.” Journal of Ethnic and Migration Studies 37 (1): 1–22. Menjivar, C. 1997. “Immigrant Kinship Networks and the Impact of the Receiving Context: Salvadorians in San Francisco in the Early 1990s.” Social Problems 44 (1): 104–123. Mon, M. M. 2010. “Burmese Female Migrant Workers in Thailand: Managing Transnational Networks and Identity.” In Civil Society and Religion in Burma, edited by K. Hlaing, U. Nwe, Y. Tuns, T. Oo, and U. Than, 269–302. Dictionary of Asia Pacific Migration, ISEAS (Institute of Southeast Asian Studies) Publishing, Singapore. Nah, A. 2014. “Contesting Citizenship Rights in Malaysia.” In Claiming Citizenship Rights in

Southeast Asia, edited by J. Grugel and E. Uhlin, 115–136. New York: Routledge, Taylor & Francis Group. Nawyn, S. 2006. “Faith, Ethnicity, and Culture in Refugee Resettlement.” American Behavioral Scientist 49 (11): 1509–1527. Ong, A. 2003. Buddha is Hiding: Refugees, Citizenship, the New America. Los Angeles: University of California Press. Poros, M. 2011. Modern Migrations: Gujarati Indian Networks in New York and London. Palo Alto, CA: Stanford University Press. Portes, A., and R. Rumbaut. 2006. Immigrant America: A Portrait. 3rd ed. Los Angeles: University of California Press. Rieffel, L., ed. 2010. Myanmar/Burma: Inside Challenges, Outside Interests. Washington, DC: Brookings Institute Press. Schapendonk, J. 2012. “Turbulent Trajectories: African Migrants on Their Way to the European Union.” Societies 2 (2): 27–41. Snyder, S. 2011. “Un/settling Angels: Faith-based Organizations and Asylum-seeking in the UK.” Journal of Refugee Studies 24 (3): 565–585. Tilly, C. 2007. “Trust Networks in Transnational Migration.” Sociological Forum 22 (1): 3–24. Townsend, J., and C. Oomen. 2015. “Before the Boat: Understanding the Migrant Journey.” Migration Policy Institute (May). http://www.migrationpolicy.org/research/boat-understandingmigrant-journey. Tress, M. 1991. “Soviet Jews in the Federal Republic of Germany: The Rebuilding of a Community.” Jewish Journal of Sociology 33 (1): 39–54. US Department of State. 2016. Proposed Refugee Admissions for Fiscal Year 2017: Report to the Congress. US Department of State, Homeland Security and Health and Human Services. Walton, M., and S. Hayward. 2014. “Contesting Buddhism Narratives: Democratization, Nationalism, and Communal Violence in Myanmar.” East West Center Policy Studies No. 71, Honolulu, Hawaii. Zolberg, A., A. Suhrke, and S. Aguayo. 1989. Escape from Violence. Oxford: Oxford University Press. Zong, J., and J. Batalova. 2015. Refugees and Asylees in the United States. Migration Policy Institute (October). http://www.migrationpolicy.org/article/refugees-and-asylees-united-states.

JOURNAL OF ETHNIC AND MIGRATION STUDIES 19 `;
